[package]
name = "prometheus-rs"
version = "0.1.0"
authors = ["Chase Wilson <me@chasewilson.dev>"]
edition = "2018"

[dependencies.fxhash]
version = "0.2.1"

[dev-dependencies.once_cell]
version = "1.4.0"
